### PR TITLE
Fix outline width for worldCoordinates outline mode

### PR DESCRIPTION
**Pull request by hiltonm**
According to the VRM spec when the outline width mode is worldCoordinates, the outlineWidthFactor is saved as meters. The shader param works with centimeters though and I believe that is correct, so we just need to convert these during import/export.

Currently, when you set on vroid an outline of 0.2cm it gets saved as 0.002m and when it gets imported here the value is clamped to 0.01cm since that is the minimum value for the shader param.

### CODE REVIEW

**Comment by fire** [comment]
If @lyuma hasn't check this tomorrow I'll check it and/or merge it.

**Comment by lyuma** [comment]
I noticed this commit only changes logic for VRM 1.0
Is any equivalent change needed for VRM 0.0?

**Comment by hiltonm** [comment]
I grepped the spec and this repo and found nothing about it. Do you still support 0.0 here? I did check exporting a vrm 0.0 file from vroid and there is an _OutlineWidth parameter with the outline in *centimeters* in the json. Does that mean it is all good?

**Comment by fire** [comment]
@lyuma Can you check this?

**Review by lyuma — APPROVED** [review]

**Comment by lyuma** [comment]
Thanks for the ping. Originally I was thinking of adapting VRM 0 materials to be in the VRM 1 format (meters), but I couldn't figure out a way to do that without compatibility breakage (affecting existing imports) so this way is safest.

**Pull request merged**
